### ISSUE TITLE
Mac OSX - Add libav in requirements.txt 

### ISSUE THREAD

**Issue by peveloper** [yask123/Instant-Music-Downloader#40]
Tried to install for OSX Yosemite, got:

```
ERROR: ffprobe or avprobe not found. Please install one.
```

Please include libav as requirement.

**Comment by yask123** [comment]
Thats right, I'll add it.

**Comment by yask123** [comment]
Fixed in 9beceb116f7117034ca00d00158800ccf3a8e5e2

**Comment by voghDev** [comment]
What's the manual solution for this problem? I'm still getting it

How do I manually install ffprobe / avprobe?
